#sudo: required
sudo: false

os:
  - linux
#  - osx

language: c

compiler:
- gcc
#  - clang

addons:
  apt:
    packages:
#    - alien

cache:
  directories:
  - download-cache

script:
  - ./.travis.install.sh download-cache
  - ./build-ftw.sh liblvrt.so.14 $TRAVIS_BUILD_DIR/download-cache/usr/local/lib64/LabVIEW-2014-64/

matrix:
  allow_failures:
    - os: osx
