version: 1.0.{build}
configuration: Debug
before_build:
  - git submodule update --init
  - mkdir "%APPVEYOR_BUILD_FOLDER%\build"
  - cd "build"
  - cmake -G "Visual Studio 12" %APPVEYOR_BUILD_FOLDER%
build_script:
  - msbuild "%APPVEYOR_BUILD_FOLDER%\build\featherweight.sln" /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test: on
